# Generated by Django 6.0.3 on 2026-09-09 00:35

import account.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Job title"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        max_length=50, null=True, unique=True, verbose_name="Job title"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=50, null=True, unique=True, verbose_name="Job title"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job title",
                "verbose_name_plural": "Job titles",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First name"),
                ),
                (
                    "first_name_uk",
                    models.CharField(
                        max_length=50, null=True, verbose_name="First name"
                    ),
                ),
                (
                    "first_name_en",
                    models.CharField(
                        max_length=50, null=True, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last name"),
                ),
                (
                    "last_name_uk",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "last_name_en",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Currently employed"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="account.position",
                        verbose_name="Job title",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Phone"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="City"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Canadian postal code.",
                                regex="^[A-Za-z]\\d[A-Za-z][ -]?\\d[A-Za-z]\\d$",
                            )
                        ],
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("AB", "Alberta"),
                            ("BC", "British Columbia"),
                            ("MB", "Manitoba"),
                            ("NB", "New Brunswick"),
                            ("NL", "Newfoundland and Labrador"),
                            ("NS", "Nova Scotia"),
                            ("NT", "Northwest Territories"),
                            ("NU", "Nunavut"),
                            ("ON", "Ontario"),
                            ("PE", "Prince Edward Island"),
                            ("QC", "Quebec"),
                            ("SK", "Saskatchewan"),
                            ("YT", "Yukon"),
                        ],
                        default="BC",
                        max_length=2,
                        verbose_name="Province",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Street address"
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="profiles/default.png",
                        upload_to=account.models.profile_directory_path,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="account.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="CheatSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="Name"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        max_length=100, null=True, unique=True, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cheat sheet",
                "verbose_name_plural": "Cheat sheets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CheatSheetStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Step number",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=account.models.cheatsheet_step_image_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "cheatsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="account.cheatsheet",
                        verbose_name="Cheat sheet",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_uk",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Cheat sheet step",
                "verbose_name_plural": "Cheat sheet steps",
                "ordering": ["cheatsheet", "step_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cheatsheet", "step_number"),
                        name="unique_step_number_per_cheatsheet",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSimpleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="account.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "end_day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                            (13, "13"),
                            (14, "14"),
                            (15, "15"),
                            (16, "16"),
                            (17, "17"),
                            (18, "18"),
                            (19, "19"),
                            (20, "20"),
                            (21, "21"),
                            (22, "22"),
                            (23, "23"),
                            (24, "24"),
                            (25, "25"),
                            (26, "26"),
                            (27, "27"),
                            (28, "28"),
                            (29, "29"),
                            (30, "30"),
                            (31, "31"),
                        ],
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="End day",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Enter valid hours."
                            )
                        ],
                        verbose_name="Hours",
                    ),
                ),
                (
                    "invoice_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Enter a valid invoice number."
                            ),
                            django.core.validators.MaxValueValidator(
                                99, message="Enter a valid invoice number."
                            ),
                        ],
                        verbose_name="Invoice number",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Enter a valid rate."
                            )
                        ],
                        verbose_name="Rate",
                    ),
                ),
                (
                    "start_day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                            (13, "13"),
                            (14, "14"),
                            (15, "15"),
                            (16, "16"),
                            (17, "17"),
                            (18, "18"),
                            (19, "19"),
                            (20, "20"),
                            (21, "21"),
                            (22, "22"),
                            (23, "23"),
                            (24, "24"),
                            (25, "25"),
                            (26, "26"),
                            (27, "27"),
                            (28, "28"),
                            (29, "29"),
                            (30, "30"),
                            (31, "31"),
                        ],
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Start day",
                    ),
                ),
                (
                    "gst",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Enter a valid GST percentage."
                            ),
                            django.core.validators.MaxValueValidator(
                                100, message="GST percentage cannot exceed 100."
                            ),
                        ],
                        verbose_name="GST",
                    ),
                ),
                (
                    "wsbc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Enter a valid WSBC percentage."
                            ),
                            django.core.validators.MaxValueValidator(
                                100, message="WSBC percentage cannot exceed 100."
                            ),
                        ],
                        verbose_name="WCB",
                    ),
                ),
                (
                    "gst_account_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=17,
                        verbose_name="GST/HST Account Number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simple invoice",
                "verbose_name_plural": "Simple invoices",
                "ordering": ["-id"],
            },
        ),
    ]
