# Generated by Django 6.0.3 on 2026-04-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "Position", "verbose_name_plural": "Positions"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
    ]
