# Generated by Django 6.0.3 on 2026-04-28 19:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="profiles/default",
                upload_to=account.models.profile_directory_path,
                verbose_name="Avatar",
            ),
        ),
    ]
