# Generated by Django 6.0.3 on 2026-04-22 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_position_options_alter_employee_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="first_name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name_uk",
            field=models.CharField(max_length=50, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name_en",
            field=models.CharField(max_length=50, null=True, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name_uk",
            field=models.CharField(max_length=50, null=True, verbose_name="Last name"),
        ),
        migrations.AddField(
            model_name="position",
            name="name_en",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Job title"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="name_uk",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Job title"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
