# Generated by Django 6.0.3 on 2026-06-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_profile_phone_employee_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySimpleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSimpleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
