# Generated by Django 6.0.3 on 2026-06-03 03:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_companysimpleinvoice_employeesimpleinvoice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanySimpleInvoice",
        ),
        migrations.AlterModelOptions(
            name="employeesimpleinvoice",
            options={
                "verbose_name": "Employee simple invoice",
                "verbose_name_plural": "Employee simple invoices",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(blank=True, max_length=50, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="employee",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Canadian postal code.",
                        regex="^[A-Za-z]\\d[A-Za-z][ -]?\\d[A-Za-z]\\d$",
                    )
                ],
                verbose_name="Postal code",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NS", "Nova Scotia"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("ON", "Ontario"),
                    ("PE", "Prince Edward Island"),
                    ("QC", "Quebec"),
                    ("SK", "Saskatchewan"),
                    ("YT", "Yukon"),
                ],
                max_length=2,
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Street address"
            ),
        ),
        migrations.AddField(
            model_name="employeesimpleinvoice",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="account.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AddField(
            model_name="employeesimpleinvoice",
            name="end_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="End day",
            ),
        ),
        migrations.AddField(
            model_name="employeesimpleinvoice",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Hours",
            ),
        ),
        migrations.AddField(
            model_name="employeesimpleinvoice",
            name="invoice_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Invoice number",
            ),
        ),
        migrations.AddField(
            model_name="employeesimpleinvoice",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Rate",
            ),
        ),
        migrations.AddField(
            model_name="employeesimpleinvoice",
            name="start_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Start day",
            ),
        ),
    ]
