# Generated by Django 6.0.3 on 2026-06-20 23:53

import account.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_employeesimpleinvoice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheatSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Cheat sheet",
                "verbose_name_plural": "Cheat sheets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CheatSheetStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Step number",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=account.models.cheatsheet_step_image_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "cheatsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="account.cheatsheet",
                        verbose_name="Cheat sheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cheat sheet step",
                "verbose_name_plural": "Cheat sheet steps",
                "ordering": ["cheatsheet", "step_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cheatsheet", "step_number"),
                        name="unique_step_number_per_cheatsheet",
                    )
                ],
            },
        ),
    ]
