# Generated by Django 6.0.3 on 2026-06-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_cheatsheet_cheatsheetstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheatsheet",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="cheatsheet",
            name="name_uk",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="cheatsheetstep",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="cheatsheetstep",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
