# Generated by Django 6.0.3 on 2026-04-04 20:39

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0002_alter_employee_options_alter_position_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="team_member/default.jpg",
                        upload_to=main.models.team_member_directory_path,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="account.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
