# Generated by Django 6.0.3 on 2026-04-27 04:00

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Company name"
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(max_length=32, verbose_name="Primary phone"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Secondary phone"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("working_hours", models.TextField(verbose_name="Working hours")),
                (
                    "working_hours_uk",
                    models.TextField(null=True, verbose_name="Working hours"),
                ),
                (
                    "working_hours_en",
                    models.TextField(null=True, verbose_name="Working hours"),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        upload_to=main.models.company_favicon_upload_path,
                        verbose_name="Company favicon",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=main.models.company_logo_upload_path,
                        verbose_name="Company logo",
                    ),
                ),
                (
                    "years_on_market",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Years on the market"
                    ),
                ),
                (
                    "completed_objects_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Completed objects count"
                    ),
                ),
                (
                    "employees_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Employees count"
                    ),
                ),
                (
                    "about_description",
                    models.TextField(verbose_name="About description"),
                ),
                (
                    "about_description_uk",
                    models.TextField(null=True, verbose_name="About description"),
                ),
                (
                    "about_description_en",
                    models.TextField(null=True, verbose_name="About description"),
                ),
                (
                    "hero_badge",
                    models.CharField(max_length=50, verbose_name="Hero badge"),
                ),
                (
                    "hero_badge_uk",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Hero badge"
                    ),
                ),
                (
                    "hero_badge_en",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Hero badge"
                    ),
                ),
                ("hero_title", models.TextField(verbose_name="Hero title")),
                (
                    "hero_title_uk",
                    models.TextField(null=True, verbose_name="Hero title"),
                ),
                (
                    "hero_title_en",
                    models.TextField(null=True, verbose_name="Hero title"),
                ),
                ("hero_description", models.TextField(verbose_name="Hero description")),
                (
                    "hero_description_uk",
                    models.TextField(null=True, verbose_name="Hero description"),
                ),
                (
                    "hero_description_en",
                    models.TextField(null=True, verbose_name="Hero description"),
                ),
                (
                    "services_description",
                    models.TextField(verbose_name="Services description"),
                ),
                (
                    "services_description_uk",
                    models.TextField(null=True, verbose_name="Services description"),
                ),
                (
                    "services_description_en",
                    models.TextField(null=True, verbose_name="Services description"),
                ),
                (
                    "footer_description",
                    models.TextField(verbose_name="Footer description"),
                ),
                (
                    "footer_description_uk",
                    models.TextField(null=True, verbose_name="Footer description"),
                ),
                (
                    "footer_description_en",
                    models.TextField(null=True, verbose_name="Footer description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "telegram_url",
                    models.URLField(blank=True, verbose_name="Telegram URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, unique=True, verbose_name="Title"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        default="residential",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(max_length=150, verbose_name="Short description"),
                ),
                (
                    "short_description_uk",
                    models.TextField(
                        max_length=150, null=True, verbose_name="Short description"
                    ),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        max_length=150, null=True, verbose_name="Short description"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to=main.models.project_cover_upload_path,
                        verbose_name="Cover image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, unique=True, verbose_name="Title"),
                ),
                (
                    "title_uk",
                    models.CharField(
                        max_length=50, null=True, unique=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=50, null=True, unique=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="Description"),
                ),
                (
                    "description_uk",
                    models.TextField(
                        max_length=200, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        max_length=200, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        upload_to=main.models.service_icon_upload_path,
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.models.project_gallery_upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project image",
                "verbose_name_plural": "Project images",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_uk",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="team_member/default.jpg",
                        upload_to=main.models.team_member_directory_path,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Display order"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Is visible"),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_member",
                        to="account.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["display_order"],
            },
        ),
    ]
