# Generated by Django 6.0.3 on 2026-04-04 23:32

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_employee_options_alter_position_options_and_more"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Company name"
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(max_length=32, verbose_name="Primary phone"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Secondary phone"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("working_hours", models.TextField(verbose_name="Working hours")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=main.models.company_logo_upload_path,
                        verbose_name="Company logo",
                    ),
                ),
                (
                    "years_on_market",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Years on the market"
                    ),
                ),
                (
                    "completed_objects_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Completed objects count"
                    ),
                ),
                (
                    "employees_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Employees count"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="About")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "telegram_url",
                    models.URLField(blank=True, verbose_name="Telegram URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="teammember",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_member",
                to="account.employee",
            ),
        ),
    ]
