# Generated by Django 6.0.3 on 2026-04-28 20:01

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_teammember_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="team_member/default.jpg",
                upload_to=main.models.team_member_directory_path,
                verbose_name="Photo",
            ),
        ),
    ]
