# Generated by Django 6.0.3 on 2026-04-04 23:55

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_position_options_alter_employee_email_and_more"),
        ("main", "0002_companyprofile_alter_teammember_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Display order"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_member",
                to="account.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is visible"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="team_member/default.jpg",
                upload_to=main.models.team_member_directory_path,
                verbose_name="Photo",
            ),
        ),
    ]
