# Generated by Django 6.0.3 on 2026-06-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_teammember_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="city",
            field=models.CharField(
                default="Saanichton", max_length=50, verbose_name="City"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="postal_code",
            field=models.CharField(
                default="V8M 0B6", max_length=10, verbose_name="Postal Code"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="province",
            field=models.CharField(
                default="BC", max_length=50, verbose_name="Province"
            ),
            preserve_default=False,
        ),
    ]
