# Generated by Django 6.0.3 on 2026-04-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_teammember_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.AlterField(
            model_name="teammember",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                unique=True, verbose_name="Display order"
            ),
        ),
    ]
