# Generated by Django 6.0.3 on 2026-04-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_teammember_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="footer_description",
            field=models.TextField(blank=True, verbose_name="Footer description"),
        ),
    ]
