# Generated by Django 6.0.3 on 2026-04-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_companyprofile_footer_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="hero_description",
            field=models.TextField(blank=True, verbose_name="Hero description"),
        ),
    ]
