# Generated by Django 6.0.3 on 2026-04-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_companyprofile_hero_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="hero_badge",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Hero badge"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="hero_title",
            field=models.TextField(blank=True, verbose_name="Hero title"),
        ),
    ]
