# Generated by Django 6.0.3 on 2026-04-07 02:50

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_companyprofile_hero_badge_companyprofile_hero_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="services_description",
            field=models.TextField(blank=True, verbose_name="Services description"),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        upload_to=main.models.service_icon_upload_path,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "company_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="main.companyprofile",
                        verbose_name="Company profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company_profile", "title"),
                        name="unique_service_title_per_company",
                    )
                ],
            },
        ),
    ]
