# Generated by Django 6.0.3 on 2026-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_companyprofile_services_description_service"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="service",
            name="unique_service_title_per_company",
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=50, unique=True, verbose_name="Title"),
        ),
        migrations.RemoveField(
            model_name="service",
            name="company_profile",
        ),
    ]
