# Generated by Django 6.0.3 on 2026-04-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_service_unique_service_title_per_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, max_length=160, verbose_name="Description"
            ),
        ),
    ]
