# Generated by Django 6.0.3 on 2026-04-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_service_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="about",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="about_description",
            field=models.TextField(blank=True, verbose_name="About description"),
        ),
    ]
