# Generated by Django 6.0.3 on 2026-04-09 00:03

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_companyprofile_about_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, unique=True, verbose_name="Title"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        default="residential",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=255, verbose_name="Short description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to=main.models.project_cover_upload_path,
                        verbose_name="Cover image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.models.project_gallery_upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project image",
                "verbose_name_plural": "Project images",
                "ordering": ["-id"],
            },
        ),
    ]
