# Generated by Django 6.0.3 on 2026-04-09 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_project_projectimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.TextField(max_length=150, verbose_name="Short description"),
        ),
    ]
