# Generated by Django 6.0.3 on 2026-04-15 23:15

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_project_created_at_alter_project_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="favicon",
            field=models.ImageField(
                blank=True,
                upload_to=main.models.company_favicon_upload_path,
                verbose_name="Company favicon",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                upload_to=main.models.company_logo_upload_path,
                verbose_name="Company logo",
            ),
        ),
    ]
