# Generated by Django 6.0.3 on 2026-04-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_service_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=50, unique=True, verbose_name="Title"),
        ),
    ]
