# Generated by Django 6.0.3 on 2026-04-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_service_description_alter_service_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="about_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="About description"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="about_description_uk",
            field=models.TextField(
                blank=True, null=True, verbose_name="About description"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="footer_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Footer description"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="footer_description_uk",
            field=models.TextField(
                blank=True, null=True, verbose_name="Footer description"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="hero_badge_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Hero badge"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="hero_badge_uk",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Hero badge"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="hero_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hero description"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="hero_description_uk",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hero description"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="hero_title_en",
            field=models.TextField(blank=True, null=True, verbose_name="Hero title"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="hero_title_uk",
            field=models.TextField(blank=True, null=True, verbose_name="Hero title"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="services_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Services description"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="services_description_uk",
            field=models.TextField(
                blank=True, null=True, verbose_name="Services description"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="working_hours_en",
            field=models.TextField(null=True, verbose_name="Working hours"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="working_hours_uk",
            field=models.TextField(null=True, verbose_name="Working hours"),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description_en",
            field=models.TextField(
                max_length=150, null=True, verbose_name="Short description"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="short_description_uk",
            field=models.TextField(
                max_length=150, null=True, verbose_name="Short description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description_uk",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="title_en",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="title_uk",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="description_uk",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
